### PR TITLE
Make logical port scan immune to v-motion.

### LINKED ISSUE #218: Error: Unknown CPI error 'Unknown' with message 'Multiple NSX-T virtual machines found. (2)' in 'set_vm_metadata' CPI method (CPI request ID: 'cpi-801732')
**Describe the bug**

Recently we found a problem when setting up a scale-out PCF environment with 100 cell VMs, but it failed with the following error:
Task 3094 | 05:08:02 | Creating missing vms: diego_cell/a0d9cf98-2b15-4d90-b393-48c384e8df32 (63) (00:01:27)
                     L Error: Unknown CPI error 'Unknown' with message 'Multiple NSX-T virtual machines (vm-af297e1b-a651-4f4b-8250-80fa11856979) found. (2)' in 'set_vm_metadata' CPI method (CPI request ID: 'cpi-801732')

We noticed that in bosh-vsphere-cpi, it needs to find out all logical ports of a VM. It uses NSX-T fabric API to get VM information from display name.
https://github.com/cloudfoundry/bosh-vsphere-cpi-release/blob/master/src/vsphere_cpi/lib/cloud/vsphere/nsxt_provider.rb#L304

Due to some reason (e.g. DRS triggering vMotion), NSX-T fabric API sometimes returns multiple VMs under the same name, from the code above I can see cpi actually can deal with this case. It keeps retrying until NSX-T returns exactly 1 VM. The retry count seems to be 20 by default, and interval is 1s.

In NSX-T 2.5.0 release, the longest time for multiple VMs under the same name is ~ 1 minute.
 
Maybe let’s just increase the retry count to adapt to NSX-T 2.5.0 release? 

**To Reproduce**
1. Create PAS setup with NSX-T 2.5.0 
2. Scale diego-cell in testbed.
3. While creating any VM in vCenter, bosh CPI gave below error.

**CPI Error Log**

Error: Unknown CPI error 'Unknown' with message 'Multiple NSX-T virtual machines (vm-af297e1b-a651-4f4b-8250-80fa11856979) found. (2)' in 'set_vm_metadata' CPI method (CPI request ID: 'cpi-801732')

**Release Version & Related Info (please complete the following information):**
 - CPI Version : 
 - BOSH Director Version : v2.5.1-build.169
 - Stemcell Name & Version : ubuntu-xenial 250.21
 - vCenter Version: 6.7U2
 - NSX T Version: 2.5.0

### PR DESCRIPTION
**Pull request by EleanorRigby**
- NSX-T can retain multiple VM copies for the same name
for a minute. Modifies algorithm to try the best effort or wait for 62
seconds max.

`COVERAGE=1 ./bin/test-unit spec/unit/cloud/vsphere/nsxt_provider_spec.rb`
 100% test covergae for changed code.

[#152045884](https://www.pivotaltracker.com/story/show/152045884)

## Related PR and Issues
Fixes #218 

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Unit Test
No suitable way to simulate in real integration tests. An attempt can be made to v-motion a vm and then try to call `logical_ports(v-motioned_vm)` after a few seconds in a separate thread. Unit tests are sufficient for fix.

# Checklist:

- [x] My code follows the standard ruby style guide
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: src/vsphere_cpi/lib/cloud/vsphere/nsxt_provider.rb [hunk 1]
```diff
@@ -303,15 +304,31 @@ def retrieve_nsgroups(nsgroup_names)
 
     def logical_ports(vm)
       Bosh::Retryable.new(
-        tries: @max_tries,
-        sleep: ->(try_count, retry_exception) { @sleep_time },
+        tries: [@max_tries, NSXT_MULTI_VM_COPY_RETRY].max,
```
Comment (nehagjain15) [inline src/vsphere_cpi/lib/cloud/vsphere/nsxt_provider.rb]: Can you just use nsxt values here instead and on  next line also?
If @max_tries and @sleep_time are not being used anywhere you could remove them
